name: 'Generate Resume From LaTeX'
on: push
defaults:
  run:
    working-directory: .
jobs:
  build_deploy:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Tex to PDF
        uses: ./actions/laTeX2PDF
        env:
          OUT_DIR: public

      - name: Download artifacts
        uses: actions/upload-artifact@v2
        with:
          name: files
          path: public/

      - name: Commit PDF
        id: commit
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions"
          git add *.pdf
          if [-z "$(git status --porcelain)"]; then
            echo "::set-output name=push::false"
          else
            git commit -m "Last updated on $(date '+%Y-%m-%d')" -a
            echo "::set-output name=push::true"
          fi
        shell: bash

      - name: Push changes
        if: steps.commit.outputs.push == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}